# Generated by Django 2.2.16 on 2022-02-03 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_auto_20220203_1727'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='following_uniq',
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.UniqueConstraint(fields=('user', 'following'), name='following_uniq'),
        ),
    ]
